const colors = {
  light: {
    text: "#0f172a",
    tint: "#1d4ed8",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#1d4ed8",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#334155",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#fbbf24",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
  },
  dark: {
    text: "#f1f5f9",
    tint: "#60a5fa",
    background: "#000000",
    foreground: "#ffffff",
    card: "#0a0a0a",
    cardForeground: "#f1f5f9",
    primary: "#818cf8",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#cbd5e1",
    muted: "#1a1a1a",
    mutedForeground: "#94a3b8",
    accent: "#fbbf24",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    border: "#1a1a1a",
    input: "#1a1a1a",
  },
  radius: 12,
};

export default colors;
